# Generated by Django 6.0.1 on 2026-01-31 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('coverage_level', models.TextField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], db_index=True)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('premium', models.DecimalField(db_index=True, decimal_places=2, max_digits=20)),
                ('duration_months', models.IntegerField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('small-commercial', 'Small Commercial')], unique=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.TextField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_subscriptions', to='insurance.insuranceplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='property_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_plans', to='insurance.propertycategory'),
        ),
    ]
