# Generated by Django 6.0.1 on 2026-01-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplan',
            name='coverage_level',
            field=models.TextField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], db_index=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='premium',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='policysubscription',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='policysubscription',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='policysubscription',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
